using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Backend.Services.Services
{
    public class TicketService
    {
        public byte[] GeneratePdf()
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.DefaultTextStyle(x => x.FontSize(20));

                    page.Header()
                        .Text("Квиток у Кіно!")
                        .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);

                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Item().Text("Фільм: Матриця 5");
                            x.Item().Text("Місце: Ряд 5, Місце 12");
                            x.Item().Text($"Ціна: 200 грн");
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by Dev 5");
                        });
                });
            });

            return document.GeneratePdf();
        }
    }
}